name: Validate

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up --build -d

      - name: Install composer
        run: docker-compose exec php composer install

      - name: Run tests
        run: docker-compose exec php composer test

      - name: Run psalm
        run: docker-compose exec php ./vendor/bin/psalm

      - name: Stop containers
        run: docker-compose down